/**
 * Keys from `theme.extend.fontSize` in tailwind.config.js — must stay in sync.
 * Used so tailwind-merge treats `text-{key}` as font-size, not text-color (otherwise
 * `text-caption-lg-regular` + `text-gray-900` collapse to one class).
 */
export const TYPOGRAPHY_FONT_SIZE_CLASS_SUFFIXES = [
  'h1-regular',
  'h1-medium',
  'h1-semi',
  'h1-bold',
  'h2-regular',
  'h2-medium',
  'h2-semi',
  'h2-bold',
  'h3-regular',
  'h3-medium',
  'h3-semi',
  'h3-bold',
  'h4-regular',
  'h4-medium',
  'h4-semi',
  'h4-bold',
  'h5-regular',
  'h5-medium',
  'h5-semi',
  'h5-bold',
  'h6-regular',
  'h6-medium',
  'h6-semi',
  'h6-bold',
  'body-regular',
  'body-medium',
  'body-semi',
  'body-bold',
  'caption-lg-regular',
  'caption-lg-medium',
  'caption-lg-semi',
  'caption-lg-bold',
  'caption-sm-regular',
  'caption-sm-medium',
  'caption-sm-semi',
  'caption-sm-bold',
  'caption-xs-regular',
  'caption-xs-medium',
  'caption-xs-semi',
  'caption-xs-bold',
] as const;
