import { IMAGES } from '@/constants/images';

import type { AdminProductRow } from '@/pages/productV2/AdminProductList/sections/AdminProductList';

export const ADMIN_PRODUCT_LIST_MOCK: AdminProductRow[] = [
  {
    id: 'mock-1',
    name: 'Supper Skinny jogger in brown',
    sizesLabel: 'Size: S, M, L',
    imageUrl: IMAGES.PRODUCT_DEMO_1,
    priceFormatted: '$80.00',
    stockLeft: 428,
    sold: 156,
    category: 'Woman',
  },
  {
    id: 'mock-2',
    name: 'Oversized hoodie — charcoal',
    sizesLabel: 'Size: XS, S, M, L, XL',
    imageUrl: IMAGES.PRODUCT_DEMO_2,
    priceFormatted: '$64.50',
    stockLeft: 210,
    sold: 89,
    category: 'Man',
  },
  {
    id: 'mock-3',
    name: 'Relaxed linen shirt',
    sizesLabel: 'Size: S, M, L',
    imageUrl: IMAGES.PRODUCT_DEMO_1,
    priceFormatted: '$59.00',
    stockLeft: 132,
    sold: 44,
    category: 'Man',
  },
  {
    id: 'mock-4',
    name: 'Ribbed knit midi dress',
    sizesLabel: 'Size: XS, S, M',
    imageUrl: IMAGES.PRODUCT_DEMO_2,
    priceFormatted: '$72.00',
    stockLeft: 95,
    sold: 201,
    category: 'Woman',
  },
  {
    id: 'mock-5',
    name: 'Lightweight packable jacket',
    sizesLabel: 'Size: M, L, XL',
    imageUrl: IMAGES.PRODUCT_DEMO_1,
    priceFormatted: '$118.00',
    stockLeft: 56,
    sold: 12,
    category: 'Man',
  },
  {
    id: 'mock-6',
    name: 'Canvas tote — natural',
    sizesLabel: 'One size',
    imageUrl: IMAGES.PRODUCT_DEMO_2,
    priceFormatted: '$34.00',
    stockLeft: 512,
    sold: 340,
    category: 'Accessories',
  },
  {
    id: 'mock-7',
    name: 'Kids fleece zip hoodie',
    sizesLabel: 'Size: 4Y, 6Y, 8Y, 10Y',
    imageUrl: IMAGES.PRODUCT_DEMO_1,
    priceFormatted: '$42.00',
    stockLeft: 78,
    sold: 55,
    category: 'Kids',
  },
  {
    id: 'mock-8',
    name: 'Merino crewneck sweater',
    sizesLabel: 'Size: S, M, L, XL',
    imageUrl: IMAGES.PRODUCT_DEMO_2,
    priceFormatted: '$96.00',
    stockLeft: 164,
    sold: 72,
    category: 'Woman',
  },
];
